# Generated by Django 4.0.6 on 2022-08-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bithumbUI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=200, null=True)),
                ('api_key', models.TextField()),
                ('secret_key', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='API_KEY',
        ),
        migrations.DeleteModel(
            name='Secret_Key',
        ),
    ]
