# Generated by Django 4.0.6 on 2022-08-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bithumbUI', '0002_api_delete_api_key_delete_secret_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='content',
        ),
    ]
