# Generated by Django 4.0.6 on 2022-08-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bithumbUI', '0003_remove_api_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api_key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='api',
            name='secret_key',
            field=models.CharField(max_length=50),
        ),
    ]
